"""Generate Performance Qualification (PQ) protocol Word draft."""

from __future__ import annotations

from pathlib import Path

from validation.docx_util import (
    add_bullets,
    add_cover,
    add_heading,
    add_para,
    add_signature_block,
    add_table,
    dated_filename,
    new_document,
    save_document,
)
from validation.inventory import SystemInventory


def write_pq(inv: SystemInventory, out_dir: Path, stamp: str) -> Path:
    doc = new_document()
    add_cover(
        doc,
        doc_title="Performance Qualification (PQ) Protocol",
        doc_code="SLS-VAL-PQ",
        generated_at=inv.generated_at,
    )

    add_heading(doc, "1. Purpose", level=1)
    add_para(
        doc,
        "Demonstrate that the system performs as intended in realistic lab business "
        "scenarios under normal operating conditions. This protocol defines scenarios "
        "and evidence requirements; execution and evidence collection are manual.",
    )

    add_heading(doc, "2. Preconditions", level=1)
    add_para(doc, "IQ and OQ completed (or justified deviations approved).")
    add_para(doc, "Dedicated PQ test users for reception, analyst, reviewer, admin.")
    add_para(doc, "Clean or clearly labelled PQ sample data set.")

    add_heading(doc, "3. Acceptance criteria (business)", level=1)
    add_bullets(
        doc,
        [
            "End-to-end CTR → Analyst → Reviewer → reported completes without data loss.",
            "Sample codes unique; final report references correct sample and customer.",
            "Audit log contains expected write actions for the scenario.",
            "Retention purge removes only expired samples; customers retained.",
            "Role gates prevent cross-role workspace misuse during the run.",
        ],
    )

    catalog = ", ".join(t.name for t in inv.lab_tests) or "(catalog empty)"
    scenarios = [
        (
            "PQ-01",
            "Full lab workflow (happy path)",
            "Reception creates CTR with ≥2 samples and selected catalog tests; "
            "Analyst completes protocol + worksheets; Reviewer issues Final Test Report PDF; "
            "status becomes reported for each sample.",
            "CTR PDF/DOCX filenames; sample_codes; protocol PDF/DOCX; Final Report PDF; "
            "screenshots of statuses; audit rows for request.save, protocol.upsert, "
            "result.save, report.final",
            "TC-E2E-001…, TC-REC-*, TC-ANL-*, TC-REV-*",
        ),
        (
            "PQ-02",
            "Multi-test formula path",
            f"Analyst runs a sample selecting multiple shared tests from: {catalog}. "
            "Verify calculated results match expected hand-check for at least 3 numeric tests.",
            "Worksheet screenshots; hand-calc sheet; protocol document; pytest formulas optional annex",
            "TC-FOR-*, TC-ANL-007…010",
        ),
        (
            "PQ-03",
            "Admin user lifecycle",
            "Admin creates reception/analyst/reviewer users (including dual-role), "
            "forces password change, changes roles, deactivates a user, resets password; "
            "confirm audit entries.",
            "User list screenshots; audit viewer export/screenshot; login proofs",
            "TC-ADM-*, TC-AUTH-006…",
        ),
        (
            "PQ-04",
            "RBAC under real use",
            "Each role logs in and confirms only allowed workspaces are usable; "
            "attempt forbidden pages and record denied access.",
            "Screenshots per role home/sidebar; denial messages",
            "TC-RBAC-*",
        ),
        (
            "PQ-05",
            "Sample retention & purge",
            "Create or mark sample past expires_at; confirm hidden from active queues; "
            "run cleanup (app open and/or scripts/cleanup_expired_samples.py); "
            "confirm purge audit and customer master remains.",
            "DB query/screenshot of expires_at; before/after sample lists; audit sample.purge_expired",
            "TC-RET-*",
        ),
        (
            "PQ-06",
            "Document stamp integrity",
            "Generate CTR and Protocol; verify Generated by and Date/time stamps "
            "match operator and lab timezone Asia/Kolkata. Generate Final Report and "
            "confirm no Generated by / date-time stamp on the customer document.",
            "PDF/DOCX footers attached as evidence",
            "TC-REC-017…018, TC-ANL-015, TC-REV-008…009",
        ),
    ]

    add_heading(doc, "4. PQ scenarios", level=1)
    add_table(
        doc,
        ("Scenario ID", "Title", "Description", "Evidence required", "Related TCs", "Result", "Date"),
        [(s[0], s[1], s[2], s[3], s[4], "", "") for s in scenarios],
    )

    add_heading(doc, "5. Detailed scenario sheets", level=1)
    for s in scenarios:
        add_heading(doc, f"{s[0]} — {s[1]}", level=2)
        add_table(
            doc,
            ("Field", "Value"),
            [
                ("Description", s[2]),
                ("Evidence required", s[3]),
                ("Related TCs", s[4]),
                ("Sample / request IDs used", ""),
                ("Operators (roles)", ""),
                ("Start / end time", ""),
                ("Actual outcome", ""),
                ("Pass / Fail", ""),
                ("Evidence file names attached", ""),
                ("Deviations", ""),
            ],
        )

    add_heading(doc, "6. Evidence index", level=1)
    add_table(
        doc,
        ("Evidence #", "Scenario", "File / location", "Description", "Attached (Y/N)"),
        [("", "", "", "", "") for _ in range(5)],
    )

    add_heading(doc, "7. Deviations", level=1)
    add_table(
        doc,
        ("Dev #", "Scenario", "Description", "Impact", "Disposition"),
        [("", "", "", "", "")],
    )

    pages = [f"{p.filename} ({', '.join(p.roles)})" for p in inv.pages]
    add_heading(doc, "8. Environment note", level=1)
    add_para(doc, f"Pages in this build: {'; '.join(pages) or 'n/a'}")
    add_para(
        doc,
        f"DB: {inv.docker_image} on port {inv.docker_host_port}; "
        f"audit actions available: {', '.join(inv.audit_actions)}",
    )

    add_signature_block(doc)
    path = out_dir / dated_filename("SLS_PQ", stamp)
    return save_document(doc, path)
