"""
services/audit.py
-----------------
Central audit log + display helpers for report generator stamps.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional, Union
from zoneinfo import ZoneInfo

from db.connection import get_db

# Lab local timezone for report stamps
_LAB_TZ = ZoneInfo("Asia/Kolkata")


@dataclass
class AuditRow:
    id: int
    occurred_at: datetime
    user_id: Optional[int]
    user_name: str
    action: str
    entity_table: str
    entity_id: Optional[str]
    details: Optional[str]


def actor_display_name(user: Any) -> str:
    """Prefer full_name; fall back to username; else 'system'."""
    if user is None:
        return "system"
    full = (getattr(user, "full_name", None) or "").strip()
    if full:
        return full
    username = (getattr(user, "username", None) or "").strip()
    return username or "system"


def format_stamp_datetime(when: Optional[datetime] = None) -> str:
    """Format datetime for report footers (Asia/Kolkata)."""
    dt = when or datetime.now(_LAB_TZ)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=_LAB_TZ)
    else:
        dt = dt.astimezone(_LAB_TZ)
    return dt.strftime("%Y-%m-%d %H:%M")


def now_lab() -> datetime:
    return datetime.now(_LAB_TZ)


def generator_stamp_lines(
    generated_by: str,
    generated_at: Optional[Union[datetime, str]] = None,
) -> list[str]:
    """Two lines for the bottom of PDF/DOCX reports."""
    if isinstance(generated_at, datetime):
        when = format_stamp_datetime(generated_at)
    elif generated_at:
        when = str(generated_at)
    else:
        when = format_stamp_datetime()
    name = (generated_by or "").strip() or "—"
    return [
        f"Generated by: {name}",
        f"Date / time: {when}",
    ]


def log_action(
    user_id: Optional[int],
    user_name: str,
    action: str,
    entity_table: str,
    entity_id: Optional[Union[int, str]] = None,
    details: Optional[str] = None,
) -> None:
    """
    Insert one audit_log row. Never raises to callers — audit must not
    break business writes; failures are swallowed after best-effort insert.
    """
    name = (user_name or "").strip() or "system"
    eid = None if entity_id is None else str(entity_id)
    try:
        with get_db() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO audit_log (
                        user_id, user_name, action,
                        entity_table, entity_id, details
                    ) VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (
                        user_id,
                        name,
                        (action or "").strip(),
                        (entity_table or "").strip(),
                        eid,
                        (details or "").strip() or None,
                    ),
                )
    except Exception:  # noqa: BLE001
        # Table may not exist yet on old DBs; do not block the app.
        pass


def log_from_user(
    user: Any,
    action: str,
    entity_table: str,
    entity_id: Optional[Union[int, str]] = None,
    details: Optional[str] = None,
) -> None:
    """Convenience: pull id/name from AuthUser / session-like object."""
    uid = getattr(user, "id", None) if user is not None else None
    log_action(
        user_id=uid,
        user_name=actor_display_name(user),
        action=action,
        entity_table=entity_table,
        entity_id=entity_id,
        details=details,
    )


def list_recent(limit: int = 100) -> list[AuditRow]:
    """Newest audit rows for Admin UI."""
    lim = max(1, min(int(limit), 500))
    sql = """
        SELECT id, occurred_at, user_id, user_name, action,
               entity_table, entity_id, details
          FROM audit_log
         ORDER BY occurred_at DESC
         LIMIT %s
    """
    try:
        with get_db() as conn:
            with conn.cursor() as cur:
                cur.execute(sql, (lim,))
                rows = cur.fetchall()
    except Exception:  # noqa: BLE001
        return []

    return [
        AuditRow(
            id=r[0],
            occurred_at=r[1],
            user_id=r[2],
            user_name=r[3] or "",
            action=r[4] or "",
            entity_table=r[5] or "",
            entity_id=r[6],
            details=r[7],
        )
        for r in rows
    ]
