"""
pages/2_Analyst.py
------------------
Analyst workspace:

1. Find sample by lab code or sample code/name (10-day window)
2. Fill protocol header (same 2 rows for ANY sample)
3. Appearance
4. Select a catalog test assigned by reception → same worksheet/formula
   for that test_key regardless of sample name (e.g. Moisture always identical)
5. Save / edit result (popup if required fields empty; re-save overwrites)
6. Page-1 summary from saved results → generate protocol PDF/DOCX
7. Update sample status (pending → in progress → completed)
"""

from __future__ import annotations

from datetime import date, datetime

import pandas as pd
import streamlit as st
from dotenv import load_dotenv

load_dotenv()

from db.connection import test_connection  # noqa: E402
from services.audit import (  # noqa: E402
    actor_display_name,
    format_stamp_datetime,
    log_from_user,
    now_lab,
)
from services.auth import get_session_user  # noqa: E402
from services.protocol_docx import (  # noqa: E402
    suggest_protocol_filename,
    unsaved_selected_test_names,
)
from services.protocol_pdf import generate_protocol_documents  # noqa: E402
from services.protocol_store import (  # noqa: E402
    ProtocolHeader,
    get_protocol_header,
    get_result_context,
    list_results,
    save_test_result,
    upsert_protocol_header,
)
from services.protocols.test_catalog import (
    CATEGORY_MICRO,
    CATEGORY_WATER,
    TEST_CATALOG,
    WATER_MICRO_TEST_KEYS,
    default_water_micro_procedure,
    get_test,
    is_dry_basis_test,
    moisture_ctx_key_for,
    normalize_category,
)  # noqa: E402
from services.worksheet_preview import preview_test_calculation  # noqa: E402
from services.samples import (  # noqa: E402
    ALLOWED_STATUSES,
    SampleRecord,
    analyst_test_checklist_rows,
    assigned_test_keys_for_sample,
    get_by_code,
    list_open,
    sample_scope_for_user,
    search_open,
    update_status,
    water_analyst_test_keys,
)
from ui.auth import require_page_access  # noqa: E402
from ui.components import (  # noqa: E402
    inject_styles,
    render_db_status,
    render_hero,
    render_section_title,
)
from ui.validation import show_missing_or_error  # noqa: E402

st.set_page_config(
    page_title="S Testing Laboratory — Analyst",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)

ANALYST_SEARCH_BY = ("lab_code", "sample")

_SEARCH_LABELS = {
    "lab_code": "Lab code",
    "sample": "Sample",
}

_SEARCH_PLACEHOLDERS = {
    "lab_code": "e.g. LAB/CTR/26/001",
    "sample": "Sample code or sample name",
}


def _fmt_dt(value) -> str:
    if value is None:
        return "—"
    if isinstance(value, datetime):
        return value.strftime("%d/%m/%Y %H:%M")
    return str(value)


def _samples_table_rows(
    samples: list[SampleRecord],
    *,
    show_analyst: bool = False,
) -> list[dict]:
    """Common columns for search hits and the open queue."""
    from services.protocols.test_catalog import category_label

    rows = []
    for s in samples:
        row = {
            "Lab code": s.lab_code or "—",
            "Sample code": s.sample_code,
            "Protocol No": getattr(s, "protocol_no", "") or "—",
            "Sample name": s.sample_name or "—",
            "Category": category_label(s.category),
            "Status": s.status,
            "Expires": _fmt_dt(s.expires_at),
        }
        if show_analyst:
            row["Chemical analyst"] = s.assigned_analyst_name or "—"
            if normalize_category(s.category) == CATEGORY_WATER:
                row["Micro analyst"] = getattr(s, "assigned_micro_analyst_name", "") or "—"
        rows.append(row)
    return rows


def main() -> None:
    require_page_access("analyst")
    actor = get_session_user()

    inject_styles()
    render_hero(
        title="Analyst — Sample protocol",
        subtitle=(
            "Results are stored for <b>10 days</b>. Find by lab code or sample, "
            "then reopen and edit until expiry. Catalog tests (e.g. <b>Moisture</b>) always "
            "use the same inputs and formula. Final customer Test Report is generated by "
            "<b>Reviewer</b>."
        ),
        badge="10-day find &amp; edit",
    )

    ok, msg = test_connection()
    render_db_status(ok, msg)
    st.write("")
    if not ok:
        st.error("Database not connected.")
        st.stop()

    scope_id, scoped = sample_scope_for_user(actor)
    scope_kw = {"assigned_analyst_id": scope_id} if scoped else {}

    # ----- Find sample (lab code / sample) -----
    render_section_title(
        "1. Find sample",
        "Search within the 10-day retention window, then open to edit results."
        + (" Only samples assigned to you are shown." if scoped else ""),
    )
    if st.session_state.get("analyst_search_by") not in ANALYST_SEARCH_BY:
        st.session_state["analyst_search_by"] = ANALYST_SEARCH_BY[0]
    search_by = st.radio(
        "Search by",
        options=list(ANALYST_SEARCH_BY),
        format_func=lambda k: _SEARCH_LABELS[k],
        horizontal=True,
        key="analyst_search_by",
    )
    c1, c2 = st.columns([3, 1])
    with c1:
        search_query = st.text_input(
            _SEARCH_LABELS[search_by],
            placeholder=_SEARCH_PLACEHOLDERS[search_by],
            key="analyst_search_query",
        )
    with c2:
        st.write("")
        st.write("")
        do_search = st.button("Search", type="primary", use_container_width=True)

    selected = None
    search_hits: list[SampleRecord] = []

    if do_search:
        if not search_query.strip():
            st.warning("Enter a search term.")
        else:
            try:
                search_hits = search_open(
                    search_query, by=search_by, limit=50, **scope_kw
                )
            except Exception as exc:  # noqa: BLE001
                st.error(str(exc))
                search_hits = []
            st.session_state["analyst_search_hits"] = [
                s.sample_code for s in search_hits
            ]
            if not search_hits:
                st.warning(
                    "No matching samples in the 10-day window."
                    + (" None are assigned to you." if scoped else "")
                )

    # Restore last search hit codes for selectbox when not re-searching this run
    if not search_hits and st.session_state.get("analyst_search_hits"):
        for code in st.session_state["analyst_search_hits"]:
            rec = get_by_code(code, **scope_kw)
            if rec:
                search_hits.append(rec)

    if search_hits:
        st.dataframe(
            pd.DataFrame(
                _samples_table_rows(search_hits, show_analyst=not scoped)
            ),
            use_container_width=True,
            hide_index=True,
        )
        pick_search = st.selectbox(
            "Select from search results",
            ["—"] + [s.sample_code for s in search_hits],
            key="analyst_pick_search",
        )
        if pick_search != "—":
            selected = get_by_code(pick_search, **scope_kw)
            if selected:
                st.session_state["analyst_active_code"] = selected.sample_code

    if selected is None and st.session_state.get("analyst_active_code"):
        selected = get_by_code(st.session_state["analyst_active_code"], **scope_kw)

    status_filter = st.selectbox(
        "Queue filter",
        ["all", "pending", "in_progress", "completed"],
        format_func=lambda x: x.replace("_", " ").title() if x != "all" else "All open",
    )

    filt = None if status_filter == "all" else status_filter
    try:
        queue = list_open(limit=50, status=filt, **scope_kw)
    except Exception as exc:  # noqa: BLE001
        st.error(str(exc))
        st.info("Run: scripts/migrate_sample_assignment.sql against the database.")
        st.stop()

    render_section_title(
        "2. Open samples",
        (
            "Your assigned non-expired jobs. Select one to edit."
            if scoped
            else "All non-expired jobs. Select one to edit."
        ),
    )
    if queue:
        st.dataframe(
            pd.DataFrame(
                _samples_table_rows(queue, show_analyst=not scoped)
            ),
            use_container_width=True,
            hide_index=True,
        )
        pick = st.selectbox(
            "Select from queue",
            ["—"] + [s.sample_code for s in queue],
            key="analyst_pick_queue",
        )
        if pick != "—":
            selected = get_by_code(pick, **scope_kw)
            if selected:
                st.session_state["analyst_active_code"] = selected.sample_code

    if selected is None:
        if scoped:
            st.info("No samples assigned to you in the 10-day window.")
        return

    st.divider()
    from services.protocols.test_catalog import category_label

    st.markdown(
        f"**Active:** `{selected.sample_code}` — **{selected.sample_name}**  \n"
        f"Category: **{category_label(selected.category)}** · "
        f"Lab code: `{selected.lab_code or '—'}` · "
        f"Expires: {_fmt_dt(selected.expires_at)}"
    )

    # ----- Protocol header (reception-owned fields are read-only) -----
    render_section_title(
        "3. Protocol header",
        "Protocol No, Issued to, and Issued by are set by Reception. "
        "You enter Date of Analysis and Appearance here.",
    )
    existing = get_protocol_header(selected.id)
    received_on = (
        (existing.sample_received_on if existing else None)
        or selected.request_date
    )
    protocol_no_display = (
        (existing.protocol_no if existing else "")
        or getattr(selected, "protocol_no", "")
        or "—"
    )
    issued_to_display = (
        (existing.issued_to if existing else "")
        or selected.assigned_analyst_name
        or "—"
    )
    issued_by_display = (existing.issued_by if existing else "") or "—"
    st.caption(
        "Sample Received On (from Reception): "
        + (received_on.isoformat() if received_on else "— not set on CTR yet")
    )
    h1, h2, h3 = st.columns(3)
    with h1:
        st.text_input("Protocol No", value=protocol_no_display, disabled=True)
    with h2:
        st.text_input("Sample Issued to", value=issued_to_display, disabled=True)
    with h3:
        st.text_input("Sample Issued by", value=issued_by_display, disabled=True)

    with st.form("protocol_header_form"):
        analysis = st.date_input(
            "Date of Analysis",
            value=(existing.date_of_analysis if existing else None) or date.today(),
        )
        appearance = st.text_area(
            "Appearance",
            value=(existing.appearance_text if existing else "") or "",
            height=80,
            help="Also saved when you run the Appearance catalog test.",
        )
        save_hdr = st.form_submit_button("Save analysis date & appearance", type="primary")

    if save_hdr:
        hdr = existing or ProtocolHeader(sample_id=selected.id)
        upsert_protocol_header(
            ProtocolHeader(
                sample_id=selected.id,
                protocol_no=hdr.protocol_no or getattr(selected, "protocol_no", ""),
                issued_to=hdr.issued_to or selected.assigned_analyst_name,
                issued_by=hdr.issued_by,
                sample_received_on=received_on,
                date_of_analysis=analysis,
                appearance_text=appearance,
            ),
            actor=actor,
        )
        st.success("Analysis date and appearance saved.")

    # ----- Assigned tests -----
    cat = normalize_category(selected.category)
    is_micro = cat == CATEGORY_MICRO
    is_admin_like = not scoped
    role_keys = (
        water_analyst_test_keys(selected, scope_id, is_admin_like=is_admin_like)
        if cat == CATEGORY_WATER
        else None
    )
    assigned = assigned_test_keys_for_sample(selected, role_keys=role_keys)
    if role_keys is not None and not assigned:
        st.warning(
            "No tests are assigned to you on this water sample. "
            "Ask reception to assign you as chemical or micro analyst."
        )
        st.stop()

    results = list_results(selected.id)
    checklist_rows = analyst_test_checklist_rows(
        selected, results, role_keys=role_keys
    )
    saved_count = sum(1 for row in checklist_rows if row["Status"] == "Saved")
    total_count = len(checklist_rows)

    render_section_title(
        "4. Tests to conduct",
        "All tests assigned by Reception for this sample. Complete each pending test "
        "before generating the protocol document.",
    )
    st.caption(f"**{saved_count} of {total_count}** tests saved")
    if checklist_rows:
        st.dataframe(
            pd.DataFrame(checklist_rows),
            use_container_width=True,
            hide_index=True,
        )
        pending_names = [row["Test"] for row in checklist_rows if row["Status"] == "Pending"]
        if pending_names:
            shown = ", ".join(pending_names[:8])
            if len(pending_names) > 8:
                shown += f", … (+{len(pending_names) - 8} more)"
            st.warning(
                f"{len(pending_names)} test(s) still pending: {shown}"
            )
    else:
        st.caption("No catalog tests assigned for this sample.")

    render_section_title(
        "5. Perform catalog test",
        (
            "Pick a microbiological test, enter Result and Unit, then Calculate & save."
            if is_micro
            else "Pick a test, edit inputs if needed, then Calculate & save (overwrites within 10 days)."
        ),
    )

    labels = {k: get_test(k).name for k in assigned}
    choice = st.selectbox(
        "Select test",
        options=assigned,
        format_func=lambda k: f"{labels[k]}  —  {get_test(k).method or 'Observation Table'}",
        key="analyst_test_choice",
    )
    test = get_test(choice)

    if cat == CATEGORY_WATER and choice in WATER_MICRO_TEST_KEYS:
        st.caption(
            "Edit **Procedure** if needed (pre-filled from the reference), "
            "then enter **Result** and save."
        )

    if is_micro:
        from services.micro_report_catalog import spec_for_key

        micro_spec = spec_for_key(choice)
        st.caption(
            f"**Limits (fixed):** {micro_spec.limits} · "
            f"**Method:** {micro_spec.method}"
        )

    prior = {r.test_key: r for r in results}
    prior_inputs = prior[choice].inputs if choice in prior else {}
    prior_row = prior.get(choice)
    preview_key = f"worksheet_preview_{selected.id}_{choice}"

    def _run_save(form_inputs: dict) -> None:
        if choice == "appearance" and form_inputs.get("appearance_obs"):
            hdr = get_protocol_header(selected.id) or ProtocolHeader(sample_id=selected.id)
            hdr.appearance_text = str(form_inputs["appearance_obs"])
            upsert_protocol_header(hdr, actor=actor)
        row = save_test_result(selected.id, choice, form_inputs, actor=actor)
        st.success(f"Saved **{row.test_name}** = **{row.result_value}** {row.unit}")
        if selected.status == "pending":
            update_status(
                selected.sample_code,
                "in_progress",
                selected.analyst_remarks,
                actor=actor,
            )
        st.session_state.pop(preview_key, None)
        st.rerun()

    if is_micro:
        from services.catalog_specs import get_spec as get_catalog_spec

        cat_spec = get_catalog_spec(choice)
        fixed_unit = bool(cat_spec and not cat_spec.unit_editable)
        default_unit = ""
        if prior_row and (prior_row.unit or "").strip():
            default_unit = prior_row.unit.strip()
        elif cat_spec and cat_spec.default_unit:
            default_unit = cat_spec.default_unit
        default_value = prior_inputs.get("result_value") or (
            prior_row.result_value if prior_row else ""
        )

        with st.form("micro_result_form"):
            st.markdown(f"#### {test.name}")
            micro_inputs: dict = {}
            micro_inputs["result_value"] = st.text_input(
                "Result",
                value=str(default_value or ""),
                key=f"micro_val_{choice}",
                help="Numeric or qualitative (e.g. Absent, 3.0 x 10³).",
            )
            if fixed_unit:
                unit_display = (cat_spec.default_unit if cat_spec else "") or "cfu/gm"
                st.text_input(
                    "Unit",
                    value=unit_display,
                    disabled=True,
                    key=f"micro_unit_ro_{choice}",
                )
                micro_inputs["result_unit"] = unit_display
            else:
                micro_inputs["result_unit"] = st.text_input(
                    "Unit",
                    value=str(default_unit or ""),
                    key=f"micro_unit_{choice}",
                )
            save_micro = st.form_submit_button(
                "Calculate & save result", type="primary", use_container_width=True
            )

        if save_micro:
            try:
                _run_save(micro_inputs)
            except ValueError as exc:
                show_missing_or_error(str(exc))
            except Exception as exc:  # noqa: BLE001
                st.error(str(exc))
    else:
        formula_lines = [p.strip() for p in (test.formula_display or "").split(";") if p.strip()]
        if len(formula_lines) > 1:
            for line in formula_lines:
                st.info(f"**Formula:** {line}")
        else:
            st.info(f"**Formula:** {test.formula_display}")

        saved_ctx = get_result_context(selected.id)
        moisture_key = moisture_ctx_key_for(choice)
        saved_moisture = saved_ctx.get(moisture_key) if moisture_key else None

        if is_dry_basis_test(choice):
            if saved_moisture is None and not str(prior_inputs.get("moisture_pct") or "").strip():
                st.warning(
                    "**Moisture must be calculated and saved first.** "
                    "This test uses the Moisture % for dry-basis conversion. "
                    "Save the **Moisture** test, then return here."
                )
            elif saved_moisture is not None:
                st.caption(
                    f"Moisture from saved test: **{saved_moisture}%** (editable below if needed)"
                )

        inputs: dict = {}
        with st.form("worksheet_form"):
            st.markdown(f"#### Worksheet — {test.name}")
            for field in test.inputs:
                if field.key == "moisture_pct":
                    continue
                default = prior_inputs.get(field.key, "")
                if (
                    field.key == "procedure"
                    and choice in WATER_MICRO_TEST_KEYS
                    and not str(default or "").strip()
                ):
                    default = default_water_micro_procedure(choice)
                label = f"{field.label}" + (f" ({field.unit})" if field.unit else "")
                if field.field_type == "choice":
                    idx = 0
                    if default in field.choices:
                        idx = field.choices.index(str(default))
                    inputs[field.key] = st.selectbox(
                        label, field.choices, index=idx, key=f"in_{choice}_{field.key}"
                    )
                elif field.field_type == "text":
                    inputs[field.key] = st.text_area(
                        label, value=str(default or ""), key=f"in_{choice}_{field.key}"
                    )
                else:
                    inputs[field.key] = st.text_input(
                        label, value=str(default or ""), key=f"in_{choice}_{field.key}"
                    )

            if moisture_key:
                default_moisture = prior_inputs.get("moisture_pct") or (
                    str(saved_moisture) if saved_moisture is not None else ""
                )
                inputs["moisture_pct"] = st.text_input(
                    "Moisture % (auto-filled from saved Moisture — editable)",
                    value=str(default_moisture or ""),
                    key=f"in_{choice}_moisture_pct",
                    help="Fetched from the saved Moisture test. Edit only if an override is required.",
                )

            btn_col1, btn_col2 = st.columns(2)
            with btn_col1:
                recalc_test = st.form_submit_button(
                    "Recalculate", use_container_width=True
                )
            with btn_col2:
                save_test = st.form_submit_button(
                    "Calculate & save result", type="primary", use_container_width=True
                )

        def _run_preview(form_inputs: dict) -> None:
            preview = preview_test_calculation(selected.id, choice, form_inputs)
            if preview.error:
                show_missing_or_error(preview.error)
            else:
                st.session_state[preview_key] = preview

        if recalc_test:
            try:
                _run_preview(inputs)
            except ValueError as exc:
                show_missing_or_error(str(exc))
            except Exception as exc:  # noqa: BLE001
                st.error(str(exc))

        if save_test:
            try:
                if is_dry_basis_test(choice):
                    m_val = str(inputs.get("moisture_pct") or "").strip()
                    if not m_val and saved_moisture is None:
                        show_missing_or_error(
                            "MOISTURE_REQUIRED:Save the Moisture test before calculating this dry-basis test."
                        )
                    else:
                        _run_save(inputs)
                else:
                    _run_save(inputs)
            except ValueError as exc:
                show_missing_or_error(str(exc))
            except Exception as exc:  # noqa: BLE001
                st.error(str(exc))

        preview = st.session_state.get(preview_key)
        if preview and not preview.error:
            st.markdown("##### Calculation preview")
            for step in preview.steps:
                st.write(f"**{step.label}:** {step.value}")

    # ----- Page-1 summary -----
    render_section_title(
        "6. Page-1 result summary",
        "Saved results from DB — reopen this sample anytime within 10 days to edit.",
    )
    if not results:
        st.caption("No test results saved yet.")
    else:
        st.dataframe(
            pd.DataFrame(
                [
                    {
                        "Name of Test": r.test_name,
                        "Method of Analysis": r.method,
                        "Result": r.result_value,
                        "Unit": r.unit,
                    }
                    for r in results
                ]
            ),
            use_container_width=True,
            hide_index=True,
        )

    # ----- Generate protocol (Food / Water / Micro) -----
    render_section_title(
        "7. Generate protocol document",
        "Micro uses reference/Micro Protocol.docx; Food and Water use their category templates.",
    )
    header = get_protocol_header(selected.id)
    from services.protocol_docx import test_unsaved_display_name
    from services.micro_protocol_docx import suggest_micro_protocol_filename

    saved_keys = {
        r.test_key
        for r in results
        if (r.result_value or "").strip()
        or any(str(v).strip() for v in (r.inputs or {}).values())
    }
    keys_to_check = (
        role_keys
        if role_keys is not None
        else selected.selected_test_keys()
    )
    missing_saves = [
        test_unsaved_display_name(k)
        for k in keys_to_check
        if k in TEST_CATALOG and k not in saved_keys
    ]
    if missing_saves:
        st.warning(
            "These selected tests have no saved result yet — their worksheet "
            "Readings will be blank until you Calculate & save: "
            + ", ".join(missing_saves)
        )
    if st.button("Generate protocol document", type="primary"):
        if header is None or not (header.protocol_no or "").strip():
            st.warning(
                "Protocol number is missing. Ask reception to enter it before generating."
            )
        else:
            try:
                if missing_saves:
                    st.info(
                        "Generating with blank worksheets for: "
                        + ", ".join(missing_saves)
                    )
                gen_by = actor_display_name(actor)
                gen_at = format_stamp_datetime(now_lab())
                docx_bytes, pdf_bytes, docx_name, pdf_name, pdf_error = generate_protocol_documents(
                    selected,
                    header,
                    results,
                    generated_by=gen_by,
                    generated_at=gen_at,
                )
                st.session_state["proto_docx_bytes"] = docx_bytes
                st.session_state["proto_docx_name"] = docx_name
                st.session_state["proto_pdf_bytes"] = pdf_bytes
                st.session_state["proto_pdf_name"] = pdf_name
                st.session_state["proto_pdf_error"] = pdf_error
                log_from_user(
                    actor,
                    "report.protocol",
                    "request_samples",
                    selected.sample_code,
                )
                if pdf_bytes:
                    st.success("Protocol generated. Download Word and/or PDF below.")
                else:
                    st.warning(
                        "Word protocol generated. PDF conversion failed — "
                        "see message below. You can still download the Word file."
                    )
            except Exception as exc:  # noqa: BLE001
                st.error(str(exc))

    if st.session_state.get("proto_docx_bytes"):
        default_name = (
            suggest_micro_protocol_filename(selected)
            if is_micro
            else suggest_protocol_filename(selected)
        )
        dl1, dl2 = st.columns(2)
        with dl1:
            st.download_button(
                "Download Word protocol (.docx)",
                data=st.session_state["proto_docx_bytes"],
                file_name=st.session_state.get("proto_docx_name", default_name),
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True,
            )
        with dl2:
            if st.session_state.get("proto_pdf_bytes"):
                st.download_button(
                    "Download PDF protocol",
                    data=st.session_state["proto_pdf_bytes"],
                    file_name=st.session_state.get("proto_pdf_name", "protocol.pdf"),
                    mime="application/pdf",
                    use_container_width=True,
                )
            else:
                pdf_error = st.session_state.get("proto_pdf_error")
                if pdf_error:
                    st.warning(f"PDF not available: {pdf_error}")
                else:
                    st.caption(
                        "PDF not available. Install Microsoft Word or LibreOffice "
                        "on the PC running this app, then generate again."
                    )

    # ----- Status -----
    st.divider()
    render_section_title("8. Sample status")
    with st.form("status_form"):
        # Analyst may set pending / in_progress / completed (not reported)
        analyst_statuses = [s for s in ALLOWED_STATUSES if s != "reported"]
        current = selected.status if selected.status in analyst_statuses else "pending"
        new_status = st.selectbox(
            "Status",
            analyst_statuses,
            index=analyst_statuses.index(current),
        )
        remarks = st.text_area("Analyst remarks", value=selected.analyst_remarks or "")
        if st.form_submit_button("Update status"):
            update_status(selected.sample_code, new_status, remarks, actor=actor)
            st.success("Status updated.")
            st.rerun()


main()
