"""
pages/2_Analyst.py
------------------
Analyst workspace:

1. Find sample by lab code, sample code/name, or client name (10-day window)
2. Fill protocol header (same 2 rows for ANY sample)
3. Appearance
4. Select a catalog test assigned by reception → same worksheet/formula
   for that test_key regardless of sample name (e.g. Moisture always identical)
5. Save / edit result (popup if required fields empty; re-save overwrites)
6. Page-1 summary from saved results → generate protocol PDF/DOCX
7. Update sample status (pending → in progress → completed)
"""

from __future__ import annotations

from datetime import date, datetime

import pandas as pd
import streamlit as st
from dotenv import load_dotenv

load_dotenv()

from db.connection import test_connection  # noqa: E402
from services.audit import (  # noqa: E402
    actor_display_name,
    format_stamp_datetime,
    log_from_user,
    now_lab,
)
from services.auth import get_session_user  # noqa: E402
from services.protocol_docx import fill_protocol_docx_bytes, suggest_protocol_filename  # noqa: E402
from services.protocol_pdf import generate_protocol_pdf_bytes  # noqa: E402
from services.protocol_store import (  # noqa: E402
    ProtocolHeader,
    get_protocol_header,
    list_results,
    save_test_result,
    upsert_protocol_header,
)
from services.protocols.test_catalog import TEST_CATALOG, get_test  # noqa: E402
from services.samples import (  # noqa: E402
    ALLOWED_STATUSES,
    SEARCH_BY,
    SampleRecord,
    get_by_code,
    list_open,
    search_open,
    update_status,
)
from ui.auth import require_role  # noqa: E402
from ui.components import (  # noqa: E402
    inject_styles,
    render_db_status,
    render_hero,
    render_section_title,
)
from ui.validation import show_missing_or_error  # noqa: E402

st.set_page_config(
    page_title="S Testing Laboratory — Analyst",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)

_SEARCH_LABELS = {
    "lab_code": "Lab code",
    "sample": "Sample",
    "client": "Client name",
}

_SEARCH_PLACEHOLDERS = {
    "lab_code": "e.g. LAB/CTR/26/001",
    "sample": "Sample code or sample name",
    "client": "Customer / company name",
}


def _fmt_dt(value) -> str:
    if value is None:
        return "—"
    if isinstance(value, datetime):
        return value.strftime("%d/%m/%Y %H:%M")
    return str(value)


def _samples_table_rows(samples: list[SampleRecord]) -> list[dict]:
    """Common columns for search hits and the open queue."""
    from services.protocols.test_catalog import category_label

    return [
        {
            "Lab code": s.lab_code or "—",
            "Sample code": s.sample_code,
            "Client": s.customer_name or "—",
            "Sample name": s.sample_name or "—",
            "Category": category_label(s.category),
            "Status": s.status,
            "Expires": _fmt_dt(s.expires_at),
        }
        for s in samples
    ]


def main() -> None:
    require_role("admin", "analyst")
    actor = get_session_user()

    inject_styles()
    render_hero(
        title="Analyst — Sample protocol",
        subtitle=(
            "Results are stored for <b>10 days</b>. Find by lab code, sample, or client name, "
            "then reopen and edit until expiry. Catalog tests (e.g. <b>Moisture</b>) always "
            "use the same inputs and formula. Final customer Test Report is generated by "
            "<b>Reviewer</b>."
        ),
        badge="10-day find &amp; edit",
    )

    ok, msg = test_connection()
    render_db_status(ok, msg)
    st.write("")
    if not ok:
        st.error("Database not connected.")
        st.stop()

    # ----- Find sample (lab code / sample / client) -----
    render_section_title(
        "1. Find sample",
        "Search within the 10-day retention window, then open to edit results.",
    )
    search_by = st.radio(
        "Search by",
        options=list(SEARCH_BY),
        format_func=lambda k: _SEARCH_LABELS[k],
        horizontal=True,
        key="analyst_search_by",
    )
    c1, c2 = st.columns([3, 1])
    with c1:
        search_query = st.text_input(
            _SEARCH_LABELS[search_by],
            placeholder=_SEARCH_PLACEHOLDERS[search_by],
            key="analyst_search_query",
        )
    with c2:
        st.write("")
        st.write("")
        do_search = st.button("Search", type="primary", use_container_width=True)

    selected = None
    search_hits: list[SampleRecord] = []

    if do_search:
        if not search_query.strip():
            st.warning("Enter a search term.")
        else:
            try:
                search_hits = search_open(search_query, by=search_by, limit=50)
            except Exception as exc:  # noqa: BLE001
                st.error(str(exc))
                search_hits = []
            st.session_state["analyst_search_hits"] = [
                s.sample_code for s in search_hits
            ]
            if not search_hits:
                st.warning("No matching samples in the 10-day window.")

    # Restore last search hit codes for selectbox when not re-searching this run
    if not search_hits and st.session_state.get("analyst_search_hits"):
        for code in st.session_state["analyst_search_hits"]:
            rec = get_by_code(code)
            if rec:
                search_hits.append(rec)

    if search_hits:
        st.dataframe(
            pd.DataFrame(_samples_table_rows(search_hits)),
            use_container_width=True,
            hide_index=True,
        )
        pick_search = st.selectbox(
            "Select from search results",
            ["—"] + [s.sample_code for s in search_hits],
            key="analyst_pick_search",
        )
        if pick_search != "—":
            selected = get_by_code(pick_search)
            if selected:
                st.session_state["analyst_active_code"] = selected.sample_code

    if selected is None and st.session_state.get("analyst_active_code"):
        selected = get_by_code(st.session_state["analyst_active_code"])

    status_filter = st.selectbox(
        "Queue filter",
        ["all", "pending", "in_progress", "completed"],
        format_func=lambda x: x.replace("_", " ").title() if x != "all" else "All open",
    )

    filt = None if status_filter == "all" else status_filter
    try:
        queue = list_open(limit=50, status=filt)
    except Exception as exc:  # noqa: BLE001
        st.error(str(exc))
        st.info("Run: scripts/migrate_protocol.sql against the database.")
        st.stop()

    render_section_title(
        "2. Open samples",
        "All non-expired jobs (lab code + client shown). Select one to edit.",
    )
    if queue:
        st.dataframe(
            pd.DataFrame(_samples_table_rows(queue)),
            use_container_width=True,
            hide_index=True,
        )
        pick = st.selectbox(
            "Select from queue",
            ["—"] + [s.sample_code for s in queue],
            key="analyst_pick_queue",
        )
        if pick != "—":
            selected = get_by_code(pick)
            if selected:
                st.session_state["analyst_active_code"] = selected.sample_code

    if selected is None:
        return

    st.divider()
    from services.protocols.test_catalog import category_label

    st.markdown(
        f"**Active:** `{selected.sample_code}` — **{selected.sample_name}**  \n"
        f"Category: **{category_label(selected.category)}** · "
        f"Lab code: `{selected.lab_code or '—'}` · Client: **{selected.customer_name or '—'}** · "
        f"Expires: {_fmt_dt(selected.expires_at)}"
    )

    # ----- Protocol header (same 2 rows for any sample) -----
    render_section_title(
        "3. Protocol header (same for any sample)",
        "Protocol No / Issued to / Issued by / Received / Analysis date.",
    )
    existing = get_protocol_header(selected.id)
    with st.form("protocol_header_form"):
        h1, h2, h3 = st.columns(3)
        with h1:
            protocol_no = st.text_input(
                "Protocol No",
                value=(existing.protocol_no if existing else "") or "",
            )
        with h2:
            issued_to = st.text_input(
                "Sample Issued to",
                value=(existing.issued_to if existing else "") or "",
            )
        with h3:
            issued_by = st.text_input(
                "Sample Issued by",
                value=(existing.issued_by if existing else "") or "",
            )
        d1, d2 = st.columns(2)
        with d1:
            received = st.date_input(
                "Sample Received On",
                value=(existing.sample_received_on if existing else None)
                or selected.request_date
                or date.today(),
            )
        with d2:
            analysis = st.date_input(
                "Date of Analysis",
                value=(existing.date_of_analysis if existing else None) or date.today(),
            )
        appearance = st.text_area(
            "Appearance",
            value=(existing.appearance_text if existing else "") or "",
            height=80,
            help="Also saved when you run the Appearance catalog test.",
        )
        save_hdr = st.form_submit_button("Save header & appearance", type="primary")

    if save_hdr:
        upsert_protocol_header(
            ProtocolHeader(
                sample_id=selected.id,
                protocol_no=protocol_no,
                issued_to=issued_to,
                issued_by=issued_by,
                sample_received_on=received,
                date_of_analysis=analysis,
                appearance_text=appearance,
            ),
            actor=actor,
        )
        st.success("Protocol header saved.")

    # ----- Assigned tests + worksheet -----
    keys = selected.selected_test_keys()
    if not keys:
        # Fallback: try match names from tests_to_perform
        keys = list(TEST_CATALOG.keys())

    render_section_title(
        "4. Perform catalog test",
        "Pick a test, edit inputs if needed, then Calculate & save (overwrites within 10 days).",
    )

    # Restrict to reception selection when available
    assigned = [k for k in keys if k in TEST_CATALOG] or list(TEST_CATALOG.keys())
    labels = {k: TEST_CATALOG[k].name for k in assigned}
    choice = st.selectbox(
        "Select test",
        options=assigned,
        format_func=lambda k: f"{labels[k]}  —  {TEST_CATALOG[k].method}",
        key="analyst_test_choice",
    )
    test = get_test(choice)

    st.info(f"**Formula:** {test.formula_display}")

    # Load prior inputs if any
    prior = {r.test_key: r for r in list_results(selected.id)}
    prior_inputs = prior[choice].inputs if choice in prior else {}

    inputs: dict = {}
    with st.form("worksheet_form"):
        st.markdown(f"#### Worksheet — {test.name}")
        for field in test.inputs:
            default = prior_inputs.get(field.key, "")
            label = f"{field.label}" + (f" ({field.unit})" if field.unit else "")
            if field.field_type == "choice":
                idx = 0
                if default in field.choices:
                    idx = field.choices.index(str(default))
                inputs[field.key] = st.selectbox(
                    label, field.choices, index=idx, key=f"in_{choice}_{field.key}"
                )
            elif field.field_type == "text":
                inputs[field.key] = st.text_area(
                    label, value=str(default or ""), key=f"in_{choice}_{field.key}"
                )
            else:
                inputs[field.key] = st.text_input(
                    label, value=str(default or ""), key=f"in_{choice}_{field.key}"
                )
        save_test = st.form_submit_button(
            "Calculate & save result", type="primary", use_container_width=True
        )

    if save_test:
        try:
            # Appearance text also mirrors into header
            if choice == "appearance" and inputs.get("appearance_obs"):
                hdr = get_protocol_header(selected.id) or ProtocolHeader(sample_id=selected.id)
                hdr.appearance_text = str(inputs["appearance_obs"])
                upsert_protocol_header(hdr, actor=actor)

            row = save_test_result(selected.id, choice, inputs, actor=actor)
            st.success(f"Saved **{row.test_name}** = **{row.result_value}** {row.unit}")
            # Mark in progress when first result saved
            if selected.status == "pending":
                update_status(
                    selected.sample_code,
                    "in_progress",
                    selected.analyst_remarks,
                    actor=actor,
                )
            st.rerun()
        except ValueError as exc:
            show_missing_or_error(str(exc))
        except Exception as exc:  # noqa: BLE001
            st.error(str(exc))

    # ----- Page-1 summary -----
    render_section_title(
        "5. Page-1 result summary",
        "Saved results from DB — reopen this sample anytime within 10 days to edit.",
    )
    results = list_results(selected.id)
    if not results:
        st.caption("No test results saved yet.")
    else:
        st.dataframe(
            pd.DataFrame(
                [
                    {
                        "Name of Test": r.test_name,
                        "Method of Analysis": r.method,
                        "Result": r.result_value,
                        "Unit": r.unit,
                    }
                    for r in results
                ]
            ),
            use_container_width=True,
            hide_index=True,
        )

    # ----- Generate protocol -----
    render_section_title("6. Generate final protocol")
    header = get_protocol_header(selected.id)
    if st.button("Generate protocol document", type="primary"):
        if header is None:
            st.warning("Save the protocol header first.")
        else:
            try:
                gen_by = actor_display_name(actor)
                gen_at = format_stamp_datetime(now_lab())
                pdf_or_docx, fname = generate_protocol_pdf_bytes(
                    selected,
                    header,
                    results,
                    generated_by=gen_by,
                    generated_at=gen_at,
                )
                mime = (
                    "application/pdf"
                    if fname.endswith(".pdf")
                    else "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                )
                st.download_button(
                    f"Download {fname}",
                    data=pdf_or_docx,
                    file_name=fname,
                    mime=mime,
                    use_container_width=True,
                )
                # Also offer raw docx
                docx_bytes = fill_protocol_docx_bytes(
                    selected,
                    header,
                    results,
                    generated_by=gen_by,
                    generated_at=gen_at,
                )
                st.download_button(
                    "Download Word protocol (.docx)",
                    data=docx_bytes,
                    file_name=suggest_protocol_filename(selected),
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    use_container_width=True,
                )
                log_from_user(
                    actor,
                    "report.protocol",
                    "request_samples",
                    selected.sample_code,
                )
            except Exception as exc:  # noqa: BLE001
                st.error(str(exc))

    # ----- Status -----
    st.divider()
    render_section_title("7. Sample status")
    with st.form("status_form"):
        # Analyst may set pending / in_progress / completed (not reported)
        analyst_statuses = [s for s in ALLOWED_STATUSES if s != "reported"]
        current = selected.status if selected.status in analyst_statuses else "pending"
        new_status = st.selectbox(
            "Status",
            analyst_statuses,
            index=analyst_statuses.index(current),
        )
        remarks = st.text_area("Analyst remarks", value=selected.analyst_remarks or "")
        if st.form_submit_button("Update status"):
            update_status(selected.sample_code, new_status, remarks, actor=actor)
            st.success("Status updated.")
            st.rerun()


main()
