"""Unit tests for CTR DOCX filler — sample table matches reference form."""

from __future__ import annotations

from datetime import date
from io import BytesIO

from docx import Document

from services.customers import Customer
from services.docx_filler import fill_docx_bytes
from services.requests import SampleRow, TestRequestData


def _ctr_request() -> TestRequestData:
    return TestRequestData(
        customer=Customer(
            customer_name="ABC Foods",
            address="1 Lab Road",
            contact_person="Ravi",
            contact_number="9876543210",
            email="ravi@example.com",
            gst_number="27AAAAA0000A1Z5",
        ),
        request_date=date(2026, 7, 30),
        lab_code="LAB/CTR/26/001",
        samples=[
            SampleRow(
                sr_no=1,
                sample_name="Jaggery",
                batch_code="B-01",
                quantity="500 g",
                parameters=(
                    "Jaggery — FSSAI — tests to be conducted "
                    "(Moisture, Total ash on dry basis)"
                ),
                package_type="fssai",
            ),
            SampleRow(
                sr_no=2,
                sample_name="Honey",
                batch_code="H-02",
                quantity="250 g",
                parameters=(
                    "Honey — Nutrition Only — tests to be conducted "
                    "(Protein, Fat)"
                ),
                package_type="nutrition_only",
            ),
        ],
    )


class TestDocxSampleTable:
    def test_table2_has_five_ctr_columns(self):
        doc = Document(BytesIO(fill_docx_bytes(_ctr_request())))
        assert len(doc.tables) >= 3
        header = [c.text.strip() for c in doc.tables[2].rows[0].cells]
        assert header == [
            "Sr. No",
            "Name of sample",
            "Code/batch no.",
            "Sample qty.",
            "Parameters",
        ]

    def test_table2_fills_sample_rows(self):
        doc = Document(BytesIO(fill_docx_bytes(_ctr_request())))
        t2 = doc.tables[2]
        row1 = [c.text.strip() for c in t2.rows[1].cells]
        assert row1[0] == "1"
        assert row1[1] == "Jaggery"
        assert row1[2] == "B-01"
        assert row1[3] == "500 g"
        assert row1[4] == "FSSAI"

        row2 = [c.text.strip() for c in t2.rows[2].cells]
        assert row2[0] == "2"
        assert row2[1] == "Honey"
        assert row2[2] == "H-02"
        assert row2[3] == "250 g"
        assert row2[4] == "Nutrition Only"

    def test_no_generator_stamp_in_ctr_docx(self):
        doc = Document(
            BytesIO(
                fill_docx_bytes(
                    _ctr_request(),
                    generated_by="Reception Test",
                    generated_at="2026-07-31 12:24",
                )
            )
        )
        body_text = "\n".join(p.text for p in doc.paragraphs)
        assert "Generated by:" not in body_text
        assert "Date / time:" not in body_text
