"""Unit tests for final report footer metadata helpers."""

from __future__ import annotations

from services.samples import format_report_footer_metadata, report_page_label


def test_format_report_footer_metadata_joins_parts():
    line = format_report_footer_metadata("Reviewer", "09/09/2026 14:30")
    assert "Generated by: Reviewer" in line
    assert "Date/time: 09/09/2026 14:30" in line


def test_report_page_label_dynamic_counts():
    assert report_page_label(with_logo=True, page=2, total=5) == "page 2 of 5"
    assert report_page_label(with_logo=False, page=3, total=4) == "pg 3 of 4"
