"""Unit tests for CTR DOCX filler — per-sample pages and verification checklist."""

from __future__ import annotations

from datetime import date
from io import BytesIO

from docx import Document

from services.customers import Customer
from services.docx_filler import fill_docx_bytes
from services.requests import SampleRow, TestRequestData
from tests.conftest import sample_verification_kwargs


def _ctr_request() -> TestRequestData:
    return TestRequestData(
        customer=Customer(
            customer_name="ABC Foods",
            address="1 Lab Road",
            contact_person="Ravi",
            contact_number="9876543210",
            email="ravi@example.com",
            gst_number="27AAAAA0000A1Z5",
        ),
        request_date=date(2026, 7, 30),
        lab_code="LAB/CTR/26/001",
        samples=[
            SampleRow(
                sr_no=1,
                sample_name="Jaggery",
                batch_code="B-01",
                quantity="500 g",
                parameters="FSSAI",
                test_keys=["moisture", "total_ash"],
                package_type="fssai",
                **sample_verification_kwargs(verify_lab_code="LAB/CTR/26/001"),
            ),
            SampleRow(
                sr_no=2,
                sample_name="Honey",
                batch_code="H-02",
                quantity="250 g",
                parameters="Basic Nutrition",
                test_keys=["bn_protein", "bn_total_fat"],
                package_type="nutrition_only",
                **sample_verification_kwargs(verify_lab_code="LAB/CTR/26/001"),
            ),
        ],
    )


class TestDocxSampleTable:
    def test_table2_has_five_ctr_columns(self):
        doc = Document(BytesIO(fill_docx_bytes(_ctr_request())))
        assert len(doc.tables) >= 3
        header = [c.text.strip() for c in doc.tables[2].rows[0].cells]
        assert header == [
            "Sr. No",
            "Name of sample",
            "Code/batch no.",
            "Sample qty.",
            "Parameters",
        ]

    def test_table2_has_only_first_sample_row(self):
        doc = Document(BytesIO(fill_docx_bytes(_ctr_request())))
        t2 = doc.tables[2]
        assert len(t2.rows) == 2
        row1 = [c.text.strip() for c in t2.rows[1].cells]
        assert row1[0] == "1"
        assert row1[1] == "Jaggery"
        assert row1[2] == "B-01"
        assert row1[3] == "500 g"
        assert row1[4] == "FSSAI"

    def test_second_sample_on_later_table_with_tests(self):
        doc = Document(BytesIO(fill_docx_bytes(_ctr_request())))
        body_text = "\n".join(p.text for p in doc.paragraphs)
        assert "Tests to be performed:" in body_text
        assert "1. Moisture" in body_text
        assert "2. Total ash on dry basis" in body_text
        assert "1. Protein" in body_text
        honey_tables = [
            t
            for t in doc.tables
            if len(t.rows) >= 2 and t.rows[1].cells[1].text.strip() == "Honey"
        ]
        assert len(honey_tables) == 1

    def test_verification_checklist_tables_appended(self):
        doc = Document(BytesIO(fill_docx_bytes(_ctr_request())))
        checklist_tables = [
            t
            for t in doc.tables
            if len(t.rows) >= 11
            and t.rows[0].cells[1].text.strip() == "Particulars"
        ]
        assert len(checklist_tables) == 2
        assert checklist_tables[0].rows[4].cells[1].text.strip() == (
            "Checked for Sample Quantity"
        )
        assert "Yes ( X )" in checklist_tables[0].rows[4].cells[2].text

    def test_no_generator_stamp_in_ctr_docx(self):
        doc = Document(
            BytesIO(
                fill_docx_bytes(
                    _ctr_request(),
                    generated_by="Reception Test",
                    generated_at="2026-07-31 12:24",
                )
            )
        )
        body_text = "\n".join(p.text for p in doc.paragraphs)
        assert "Generated by:" not in body_text
        assert "Date / time:" not in body_text
