"""Unit tests for food final report DOCX template fill."""

from __future__ import annotations

import json
from datetime import date
from io import BytesIO

from docx import Document

from services.protocol_store import ProtocolHeader, TestResultRow
from services.samples import SampleRecord
from services.test_report_food_docx import (
    FOOD_REPORT_TEMPLATE_PATH,
    HEADER_ROW_COUNT,
    fill_food_test_report_docx_bytes,
    generate_food_test_report_pdf_bytes,
)


def _sample(**overrides) -> SampleRecord:
    base = dict(
        id=1,
        request_id=1,
        sample_code="SLS-260704-0001",
        sr_no=1,
        sample_name="Jaggery",
        batch_code="B-01",
        quantity="500 g",
        parameters="FSSAI",
        tests_to_perform="",
        status="completed",
        analyst_remarks="",
        created_at=None,
        expires_at=None,
        category="food",
        tests_json=json.dumps(["moisture", "total_ash"]),
        lab_code="SLS/26/306",
        customer_name="ABC Foods",
        customer_address="Pune",
        report_format="with_logo",
        tests_with_logo_json="",
        tests_without_logo_json="",
        sampling_by_lab=False,
        package_type="fssai",
    )
    base.update(overrides)
    return SampleRecord(**base)


def _header() -> ProtocolHeader:
    return ProtocolHeader(
        sample_id=1,
        protocol_no="P-001",
        issued_to="Analyst",
        issued_by="Reception",
        sample_received_on=date(2026, 7, 4),
        date_of_analysis=date(2026, 7, 9),
        appearance_text="Brown",
    )


def _results() -> list[TestResultRow]:
    return [
        TestResultRow(
            test_key="moisture",
            test_name="Moisture",
            method="IS 15279:2003",
            unit="%",
            inputs={},
            result_value="6.00",
            result_numeric=6.0,
        ),
    ]


def _all_text(doc: Document) -> str:
    parts = [p.text for p in doc.paragraphs]
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                parts.append(cell.text)
    header = doc.sections[0].header
    for table in header.tables:
        for row in table.rows:
            for cell in row.cells:
                parts.append(cell.text)
    return "\n".join(parts)


def _body_text(doc: Document) -> str:
    return "\n".join(p.text for p in doc.paragraphs)


def test_food_template_exists():
    assert FOOD_REPORT_TEMPLATE_PATH.exists()


def test_template_page_setup_matches_dk_reference():
    doc = Document(str(FOOD_REPORT_TEMPLATE_PATH))
    sec = doc.sections[0]
    assert round(sec.page_width.inches, 2) == 8.27
    assert round(sec.left_margin.inches, 1) == 1.0
    assert round(sec.top_margin.inches, 1) == 0.2
    header_text = _all_text(doc)
    assert "TEST REPORT" in header_text
    assert "QSF No -7.8.2" in header_text
    assert "Location of sampling" in _all_text(doc)
    assert "Mfg Date" not in _all_text(doc)


def test_fill_food_report_from_template():
    docx_bytes = fill_food_test_report_docx_bytes(
        _sample(),
        _header(),
        _results(),
        generated_by="Reviewer",
        generated_at="09/09/2026 14:30",
        authorized_signatory="Dr. Surendra Nashikkar",
        checked_by="Amruta Kulkarni",
        location_of_sampling="Nashik",
        sampling_method="Customer",
    )
    doc = Document(BytesIO(docx_bytes))
    text = _all_text(doc)
    assert "CHEMICAL TEST REPORT" in text
    assert len(doc.tables) >= 2
    meta = doc.tables[0]
    assert meta.rows[8].cells[0].text.strip() == "Location of sampling"
    results_table = doc.tables[1]
    assert results_table.rows[2].cells[1].text == "Moisture"
    assert "6.00" in results_table.rows[2].cells[2].text
    assert "Dr. Surendra Nashikkar" in text
    assert "Amruta Kulkarni" in text
    assert "Nashik" in text
    assert "Disclaimer" in text
    assert "End of Report" in text
    assert "SLS-260704-0001" in text or "SLS/26/306" in text
    for i in range(HEADER_ROW_COUNT, len(results_table.rows) - 1):
        assert results_table.rows[i].cells[1].text.strip()
    footer_parts = [p.text for p in doc.sections[0].footer.paragraphs if p.text.strip()]
    assert any("Generated by: Reviewer" in t for t in footer_parts)
    assert any("Date/time: 09/09/2026" in t for t in footer_parts)
    assert any("page" in t.lower() and "of" in t.lower() for t in footer_parts)
    assert any(
        "Sample submitted by the customer" in t for t in footer_parts
    )


def test_without_logo_footer_uses_pg_label():
    docx_bytes = fill_food_test_report_docx_bytes(
        _sample(report_format="without_logo"),
        _header(),
        _results(),
        with_logo=False,
    )
    doc = Document(BytesIO(docx_bytes))
    footer_parts = [p.text for p in doc.sections[0].footer.paragraphs if p.text.strip()]
    assert any(t.strip().startswith("pg") for t in footer_parts)
    assert any("of" in t for t in footer_parts)


def test_ulr_shown_with_logo():
    docx_bytes = fill_food_test_report_docx_bytes(
        _sample(report_format="with_logo"),
        _header(),
        _results(),
        ulr_no="TC1611826000030601F",
        with_logo=True,
    )
    doc = Document(BytesIO(docx_bytes))
    assert "TC1611826000030601F" in _body_text(doc)
    assert "ULR No" in _body_text(doc)


def test_food_report_header_overrides_in_metadata_and_date():
    docx_bytes = fill_food_test_report_docx_bytes(
        _sample(parameters="FSSAI", sample_name="Kesar Gud"),
        _header(),
        _results(),
        report_date=date(2026, 9, 15),
        ulr_no="TC1611826000030601F",
        customer_name_address="DK Brothers\nMumbai",
        customer_sample_id="Kesar Gud",
        batch_no="07 (July 2026)",
        lab_code="SLS/26/562/01",
        with_logo=True,
    )
    doc = Document(BytesIO(docx_bytes))
    body = _body_text(doc)
    text = _all_text(doc)
    assert "Date: 15/09/2026" in body
    assert "TC1611826000030601F" in body
    assert "DK Brothers" in text
    assert "Mumbai" in text
    assert "Kesar Gud" in text
    assert "07 (July 2026)" in text
    assert "SLS/26/562/01" in text


def test_food_default_customer_sample_id_uses_sample_name_not_parameters():
    from services.test_report_pdf import build_test_report_data

    data = build_test_report_data(
        _sample(parameters="FSSAI", sample_name="Jaggery"),
        _header(),
        _results(),
    )
    assert data.customer_sample_id == "Jaggery"
    assert data.lab_code == "SLS-260704-0001"


def test_ulr_hidden_without_logo():
    docx_bytes = fill_food_test_report_docx_bytes(
        _sample(report_format="without_logo"),
        _header(),
        _results(),
        ulr_no="TC1611826000030601F",
        with_logo=False,
    )
    doc = Document(BytesIO(docx_bytes))
    body = _body_text(doc)
    assert "TC1611826000030601F" not in body
    assert "ULR No" not in body


def test_both_logo_report_combines_two_pages():
    sample = _sample(
        report_format="both",
        tests_with_logo_json=json.dumps(["moisture"]),
        tests_without_logo_json=json.dumps(["total_ash"]),
        tests_json=json.dumps(["moisture", "total_ash"]),
    )
    results = _results() + [
        TestResultRow(
            test_key="total_ash",
            test_name="Total Ash",
            method="IS 1288:1959",
            unit="%",
            inputs={},
            result_value="2.10",
            result_numeric=2.1,
        ),
    ]
    docx_bytes, _ = generate_food_test_report_pdf_bytes(
        sample,
        _header(),
        results,
        authorized_signatory="Dr. Surendra Nashikkar",
    )
    doc = Document(BytesIO(docx_bytes))
    text = _all_text(doc)
    assert "Moisture" in text
    assert "Total ash" in text or "/02" in text
    assert text.count("CHEMICAL TEST REPORT") >= 2
